### ISSUE TITLE
Define way to calculate score

### ISSUE THREAD

**Issue by chicobentojr** [felipemfp/racing#11]
``` ruby
score = millis / 226 * @player.speed
```

sugestion by @felipemfp

**Comment by felipemfp** [comment]
right now, it is a float. I prefer an integer... What about you, @chicobentojr ?

**Comment by chicobentojr** [comment]
@felipemfp Yeah, it's better

**Comment by felipemfp** [comment]
It could be: `score = millis / 1000 + some_value * @player.speed`.

**Comment by felipemfp** [comment]
Instead of look for a new way, I have added conversion to integer, because we would have to face some troubles. :disappointed:
