### ISSUE TITLE
Improve accelerating and braking

### ISSUE THREAD

**Issue by felipemfp** [felipemfp/racing#13]
Perhaps display the current speed...

**Comment by chicobentojr** [comment]
look in [this forum](http://gtaforums.com/topic/494178-speedometer-textures/)

**Comment by felipemfp** [comment]
Ok. We already have a speedometer, but I was thinking the player is accelerating too fast, don't you think so, @chicobentojr? Maybe we should add a simple interval like 300 milliseconds?

**Comment by chicobentojr** [comment]
@felipemfp I was thinking in a way that uses **speed** and **acceleration**. When you start the game the acceleration is high, then, when you have more speed, the acceleration will start to increase slowly.

**Comment by felipemfp** [comment]
Sure, it is more complex, but it's your choice.
