### ISSUE TITLE
Create a .exe

### ISSUE THREAD

**Issue by felipemfp** [felipemfp/racing#22]

**Comment by felipemfp** [comment]
@chicobentojr any troubles?

**Comment by chicobentojr** [comment]
@felipemfp yeah, my memory

**Comment by chicobentojr** [comment]
@felipemfp Now it's okay?

**Comment by felipemfp** [comment]
@chicobentojr, it's ok :+1: 

It's not ideal, because it doesn't work in other folders like `bin/`.

**Comment by chicobentojr** [comment]
@felipemfp It was based in this [link](https://github.com/gosu/gosu/wiki/Ruby-Packaging-on-Windows)
